[build]
  base = "/5"
  publish = "/5/dist"
  functions = "/5/functions"
  command = "yarn run build"



# Redirect a likely mistake
[[redirects]]
  from = "/edition*"
  to = "/number/:splat"
  status = 302


# proxy calls to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200



# 404s
[[redirects]]
  from = "/number*"
  to = "/edition-not-found"
  status = 404

[[redirects]]
  from = "*"
  to = "/404"
  status = 404
